### ISSUE TITLE
Macaw's doors, some doors  do not open after being placed

### ISSUE THREAD

**Issue by Arcitect-X** [KangyKSLG/Technological#34]
Some of macaw's doors do not place
metal, metal warning, metal hospital door, jail door, metal windowed door

**To Reproduce**
1. grab door and place
2. note how it does not open with right click

**Expected behavior**
Door should open with right click

**Version**
Technological 0.77.1
Macaw's Doors 1.0

**Additional context**
Fairly certain this worked earlier

**Comment by Kangy1103** [comment]
Which doors in particular? Did you try with buttons or levers?

**Comment by Arcitect-X** [comment]
I put all the doors i tested in the bug report

**Comment by Kangy1103** [comment]
Did you try buttons or levers?

**Comment by Kangy1103** [comment]
Doors open with a redstone signal (button, lever, plate etc). Closing issue
